// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtfvakRrDqU2o-NqGriBHn4AT6YreTHhY',
    appId: '1:708086793607:web:d5188fb93acfbca0d3ff22',
    messagingSenderId: '708086793607',
    projectId: 'auth-test-task-31faa',
    authDomain: 'auth-test-task-31faa.firebaseapp.com',
    storageBucket: 'auth-test-task-31faa.appspot.com',
    measurementId: 'G-ZSH4CFEGPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOoQE7xCy4v362pcKonwaDBjlbcxIrBzo',
    appId: '1:708086793607:android:ee4730d6f86d8d27d3ff22',
    messagingSenderId: '708086793607',
    projectId: 'auth-test-task-31faa',
    storageBucket: 'auth-test-task-31faa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKTcUokszxJX3wMkxQfPm9ZsqlRuolwU4',
    appId: '1:708086793607:ios:22458adda6d442ced3ff22',
    messagingSenderId: '708086793607',
    projectId: 'auth-test-task-31faa',
    storageBucket: 'auth-test-task-31faa.appspot.com',
    iosBundleId: 'com.example.authTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKTcUokszxJX3wMkxQfPm9ZsqlRuolwU4',
    appId: '1:708086793607:ios:00c4a71aa213d3aad3ff22',
    messagingSenderId: '708086793607',
    projectId: 'auth-test-task-31faa',
    storageBucket: 'auth-test-task-31faa.appspot.com',
    iosBundleId: 'com.example.authTask.RunnerTests',
  );
}
